# Generated by Django 5.2.4 on 2025-08-01 10:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
